---
- name: 'Install yum-utils'
  when: ansible_os_family == 'RedHat'
  yum:
    name: yum-utils
    state: present
  tags: y_utils

- name: 'Install yum-config-manager'
  when: ansible_os_family == 'RedHat'
  shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags: ycm
 
- name: "Install Docker OS RedHat"
  when: ansible_os_family == 'RedHat'
  yum:
    name: '{{item}}'
    state: present
  with_items: '{{docker_rh}}'
  become: yes
  tags: docker_c7

- name: "Install Repo Docker OS Debian"
  when: ansible_os_family == "Debian"
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{repo_docker_d}}'
  become: yes
  tags: repo_d_d

- name: "Install Docker OS Debian"
  when: ansible_os_family == 'Debian'
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_d}}'
  become: yes
  tags: docker_d

- name: 'Enable Docker'
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  tags: enable_docker
