---
- name: 'Script hosts.sh'
  copy:
    src: '../templates/hosts.sh'
    dest: '/home/golden/hosts.sh'
    owner: golden
    group: golden
    mode: +x
  become: yes
  tags: s_hosts

- name: 'Execute script hosts.sh'
  shell:
     cmd: '/home/golden/hosts.sh'
  become: yes
  tags: exe_scr

- name: 'Remove file'
  file:
    path: '/home/golden/hosts.sh'
    state: absent
  become: yes
  tags: rm_scr

- name: 'Disable SElinux'
  shell:
     cmd: 'setenforce 0'
  become: yes
  tags: selinux

- name: 'Set SElinux File'
  shell:
     cmd: "sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux"
  become: yes
  tags: selinux_f

- name: 'Set firewall rules on ports'
  firewalld:
    port: '{{item}}'
    permanent: yes
    state: enabled
  with_items: '{{ports}}'
  become: yes
  tags: set_fd

- name: 'ModProbe'
  shell:
     cmd: 'modprobe br_netfilter'
  become: yes
  tags: modprobe

- name: 'proc'
  shell:
     cmd: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
  become: yes
  tags: proc
