---
- name: "Install apt-transport-https"
  apt:
    name: 'apt-transport-https'
    state: present
  become: yes
  tags: ath

- name: "cgroup driver uses systemd"
  copy:
    src: '../files/daemon.json'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes
  tags: cgroup

- name: "Restart Docker"
  shell:
    cmd: 'sudo systemctl restart docker'
  become: yes
  tags: rs_docker

- name: "Config K8s"
  copy: 
    src: '../files/k8s.conf'
    dest: '/etc/sysctl.d/k8s.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes
  tags: k8s_conf

- name: "sysctl --system"
  shell:
    cmd: 'sysctl --system'
  become: yes
  tags: sysctl

- name: "if swap is On, turn to Off"
  shell:
    cmd: 'swapoff -a'
  become: yes
  tags: soff

- name: "Edit /etc/fstab"
  replace:
    path: '/etc/fstab'
    regexp: '^swap(.*)'
    replace: '# \1'
  become: yes
  tags: r_swap_in_fstab

- name: "Install apt-key.gpg"
  shell:
    cmd: 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'
  become: yes
  tags: apt-key

- name: "Config apt-key.gpg"
  shell: 
    cmd: 'echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list'
  become: yes
  tags: s_list

- name: "Update cache"
  apt:
    update_cache: yes
  become: yes
  tags: u_cache

- name: "Install Kubernetes"
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{kube}}'
  become: yes
  tags: i_k8s_d

